title: Manas Rawat's Blog
email: manas.rawat2002@gmail.com
description: > 
  A blog on Android, computer programming, maths and android.
baseurl: ""
url: https://cyource
enforce_ssl: cyource.me
github_username:  cyource
repository: cyource/cyource.github.io
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title
future: true