title: Manas Rawat
email: manas.rawat2002@gmail.com
description: > 
  A blog on Android, computer programming and more.
baseurl: ""
url: https://manasrawat.github.io
enforce_ssl: https://manasrawat.github.io
github_username:  manasrawat
repository: manasrawat/manasrawat.github.io
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
future: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: general
plugins:
  - jekyll-feed