title: River Logs
email: manas.rawat2002@gmail.com
description: > 
  A blog on Android, computer programming and more.
baseurl: ""
url: https://munowse.github.io
enforce_ssl: cyource.me
github_username:  munowse
repository: munowse/munowse.github.io
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title
future: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: general